name: Python CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          pip install snowflake-connector-python
          pip install python-dotenv

      - name: Check Python syntax
        run: |
          python -m py_compile scripts/ingest_to_snowflake.py